In [1]:
import array

In [2]:
L = list(range(10))


In [3]:
A = array.array('i', L)

In [4]:
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np


In [6]:
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 2, 3, 6, 4])


array([3.14, 2.  , 3.  , 6.  , 4.  ])

In [8]:
np.array(["sanchit", 4, 78, 4.37])


array(['sanchit', '4', '78', '4.37'], dtype='<U32')

In [9]:
# dtype = data type. To fix the data type for the array


In [11]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
for i in [2, 4, 6]:
  print(range(i, i+3))

range(2, 5)
range(4, 7)
range(6, 9)


In [15]:
np.ones(10, dtype = float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random((3,3))

array([[0.69927318, 0.27165332, 0.62517337],
       [0.1782287 , 0.79649478, 0.16290796],
       [0.03563818, 0.11100187, 0.08935404]])

In [20]:
np.random.randint(0, 10, (3, 3))


array([[8, 7, 0],
       [2, 1, 7],
       [0, 5, 4]])

In [21]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.zeros(10, dtype = np.int16)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [29]:
np.random.seed(0)

In [24]:
x1 = np.random.randint(10, size=6)

In [30]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))



In [31]:
x1


array([5, 0, 3, 3, 7, 9])

In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x3


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [39]:
print("itemsize: ", x3.itemsize, " Bytes")

itemsize:  8  Bytes


In [38]:
print("itemsize: ", x3.nbytes, " Bytes")

itemsize:  480  Bytes


In [40]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
array([5,6,4,33,22,3,2,1])

TypeError: ignored

In [42]:
x1

array([5, 0, 3, 3, 7, 9])

In [43]:
x1[3] = 3.132

In [44]:
x1

array([5, 0, 3, 3, 7, 9])

In [45]:
x1[0] = 3.212

In [46]:
x1

array([3, 0, 3, 3, 7, 9])

In [47]:
;x = np.arrange(10)

AttributeError: ignored

In [49]:
x = np.arange(10)

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x[-1:]

array([9])

In [52]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[::1, ::]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [56]:
x2[::-1, ::]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [57]:
x2[::-2, ::]

array([[1, 6, 7, 7],
       [3, 5, 2, 4]])

In [58]:
print(x2[:, 0])

[3 7 1]


In [59]:
print(x2[0, :])

[3 5 2 4]


In [62]:
x2_sub = x2[:2, :2]

In [63]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [64]:
x2_sub[0,0] = 99

In [66]:
print(x2_sub)

[[99  5]
 [ 7  6]]


In [67]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [68]:
x2_sub = x2[:2, :2].copy()

In [69]:
x2_sub[0,0] = 122

In [70]:
x2_sub

array([[122,   5],
       [  7,   6]])

In [71]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
grid = np.arange(1, 10)

In [74]:
grid = np.arange(1, 10).reshape(3, 3)

In [75]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [80]:
grid = np.array([[1,2,3], [4,5,6]])

In [81]:
print(grid)

[[1 2 3]
 [4 5 6]]


In [82]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
x = np.array([1,2,3])

In [84]:
grid = np.array([[9,8,7], [6,5,4]])

In [85]:
x = [1,2,3,99,99,3,2,1]

In [86]:
x1,x2,x3 = np.split(x, [3,5])

In [87]:
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [88]:
grid = np.arange(16).reshape((4,4))

In [89]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])